### ISSUE TITLE
Please add unminified source and clarify license, thanks!

### ISSUE THREAD

**Issue by ghost** [mustafaozcan/jquery.fixedtableheader#1]
It would be nice to have also the original source code here, e.g. https://gist.github.com/donut/920491

Also, it would be nice to mention which version of GPL you mean, e.g. "GPL3 or later" or "GPL2 only" or whatever. Not very important, because MIT is already clear, but anyway...

Many thanks in advance!

**Comment by mustafaozcan** [comment]
Fixed.
